# Generated by Django 6.0.5 on 2026-05-26 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN_SYS', 'Admin Système'), ('ADMIN_METIER', 'Admin Métier'), ('ECOLE', 'École Privée'), ('MINISTERE', 'Ministère de Tutelle'), ('ETUDIANT', 'Parent / Étudiant')], default='ETUDIANT', max_length=20),
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('niveaux', models.CharField(blank=True, max_length=100, null=True)),
                ('capacite_eleves', models.IntegerField(default=0)),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_ecole', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, max_length=20, null=True)),
                ('education_parent', models.CharField(blank=True, max_length=100, null=True)),
                ('lunch_plan', models.CharField(blank=True, max_length=50, null=True)),
                ('note_math', models.IntegerField(default=0)),
                ('note_lecture', models.IntegerField(default=0)),
                ('note_ecriture', models.IntegerField(default=0)),
                ('ecole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='core.ecole')),
            ],
        ),
    ]
