# Generated by Django 6.0.5 on 2026-05-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN_SYS', 'Admin Système'), ('ADMIN_METIER', 'Admin Métier'), ('ECOLE', 'École Privée'), ('MINISTERE', 'Ministère de Tutelle'), ('ETUDIANT', 'Parent / Étudiant')], default='ETUDIANT', max_length=20),
        ),
    ]
