# Generated by Django 6.0.5 on 2026-05-27 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_utilisateur_role_ecole_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='utilisateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_etudiant', to=settings.AUTH_USER_MODEL),
        ),
    ]
