# Generated by Django 6.0.5 on 2026-05-29 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_utilisateur_role'),
        ('core', '0003_etudiant_utilisateur'),
    ]

    operations = [
    ]
