# Generated by Django 6.0.5 on 2026-06-15 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20260529_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('type_demande', models.CharField(choices=[('INSCRIPTION', 'Inscription'), ('RENOUVELLEMENT', 'Renouvellement'), ('MODIFICATION', 'Modification'), ('TRANSFERT', 'Transfert')], default='INSCRIPTION', max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours de traitement'), ('VALIDE_ADMIN', 'Validé par Admin Métier'), ('VALIDE_MINISTERE', 'Validé par Ministère'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=30)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('date_traitement_admin', models.DateTimeField(blank=True, null=True)),
                ('date_traitement_ministere', models.DateTimeField(blank=True, null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='demandes/')),
                ('nombre_fichiers', models.IntegerField(default=0)),
                ('commentaire_admin', models.TextField(blank=True, null=True)),
                ('commentaire_ministere', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='core.ecole')),
                ('traite_par_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees_admin', to=settings.AUTH_USER_MODEL)),
                ('traite_par_ministere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees_ministere', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_depot'],
            },
        ),
    ]
