# Generated by Django 6.0.5 on 2026-06-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='niveau',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
