# Generated by Django 6.0.5 on 2026-06-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_etudiant_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='date_creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecole',
            name='date_demande',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ecole',
            name='date_validation_admin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecole',
            name='date_validation_ministere',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecole',
            name='document_autorisation',
            field=models.FileField(blank=True, null=True, upload_to='ecoles/documents/'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='document_identite',
            field=models.FileField(blank=True, null=True, upload_to='ecoles/documents/'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='document_justificatif',
            field=models.FileField(blank=True, null=True, upload_to='ecoles/documents/'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ecole',
            name='site_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecole',
            name='statut_inscription',
            field=models.CharField(choices=[('EN_ATTENTE_ADMIN', 'En attente Admin Métier'), ('VALIDE_ADMIN', 'Validé par Admin Métier'), ('VALIDE_MINISTERE', 'Validé par Ministère'), ('ACTIVE', 'Active'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE_ADMIN', max_length=30),
        ),
        migrations.AddField(
            model_name='ecole',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
