# Generated by Django 6.0.5 on 2026-06-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ecole_date_creation_ecole_date_demande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='est_demande_inscription',
            field=models.BooleanField(default=False),
        ),
    ]
