# Generated by Django 6.0.5 on 2026-06-16 17:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ecole_est_demande_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='note_anglais',
            field=models.IntegerField(default=core.models.note_aleatoire),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='note_histoire',
            field=models.IntegerField(default=core.models.note_aleatoire),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='note_informatique',
            field=models.IntegerField(default=core.models.note_aleatoire),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='note_physique',
            field=models.IntegerField(default=core.models.note_aleatoire),
        ),
    ]
