# Generated by Django 6.0.5 on 2026-06-19 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_etudiant_note_anglais_etudiant_note_histoire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='documents',
        ),
        migrations.CreateModel(
            name='DocumentDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='demandes/fichiers/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers_joints', to='core.demande')),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('matiere', models.CharField(max_length=100)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignants', to='core.ecole')),
            ],
        ),
    ]
