# Generated by Django 6.0.5 on 2026-06-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_demande_documents_documentdemande_enseignant'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='niveau',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
